### PR TITLE
Add global state management

### PR DESCRIPTION
**Pull request by Totodore**
## This PR adds global state management as well as a `State` extractor to get the state in any handlers.

Note : Before merging this PR, it is necessary to use dynamics handler for the `on_disconnect` function. Otherwise it wont be possible to use the state in these handlers.

Currently it is not possible to use the references in extractors because of the following problem :
In the `ConnectHandler` implementation below for any function with arguments that implements `FromConnectParts` and are specified by values. To add a lifetime to extractors we could add a lifetime on the trait `FromConnectParts`. The problem is that the provided lifetime should be the one declared with the `for<'a>` corresponding to the function and its scope is rather limited.
```rust
impl<A, F, $($ty,)*> ConnectHandler<A, (private::Sync, $($ty,)*)> for F
        where
            F: for<'a> FnOnce($($ty,)*) + Send + Sync + Clone + 'static,  // The lifetime 'a should be propagated to the `FromConnectParts` 
            A: Adapter,                                                   // ---------------------------------------
            $( $ty: FromConnectParts<'a, A> + Send, )*                    // <----- here
        {
            fn call(
                &self,
                s: Arc<Socket<A>>,
                auth: Option<String>,
                state: &Arc<dyn std::any::Any + Send + Sync>)
            {
                $(
                    let $ty = match $ty::from_connect_parts(&s, &auth,  state) {
                        Ok(v) => v,
                        Err(_e) => {
                            #[cfg(feature = "tracing")]
                            tracing::error!("Error while extracting data: {}", _e);
                            return;
                        },
                    };
                )*

                (self.clone())($($ty,)*);
            }
        }
```

Because of this issue any given state must be clonable so it can be given by value to the handlers.

## Close :
* #178

### CODE REVIEW

**Comment by tausifcreates** [comment]
States are cheap to clone right? So this should be fine.

**Comment by Totodore** [comment]
No, it depends if the state is put in an `Arc` or not

**Comment by tausifcreates** [comment]
Oh, great! I assumed you were going to implement clone-able state because of the said limitations 😄

**Comment by Totodore** [comment]
Superseded by #194

**Pull request closed without merging**
