### PR TITLE
Examples + Refactoring

### PR DESCRIPTION
**Pull request by Totodore**
This pull requests adds :
* Hyper echo examples
* Axum chat app example (with a `CorsLayer`configured #16)
* Some benchmarks for EngineIo polling requests
* Socket Extensions to store data inside sockets. 

It also contains a refactoring of the architecture, between SocketIo Client & the EngineIo structs there was a circular dependency that is now removed.

### CODE REVIEW

**Comment by sleeyax** [comment]
Hi, I'm trying out the changes in this branch and the following simple example isn't working on my end. Nothing is ever logged to any console so I suppose the websocket connection is never made. Not sure how I can debug this. What am I doing wrong?

Server:

```rust
use axum::routing::get;
use axum::Server;
use serde_json::Value;
use socketioxide::{Namespace, SocketIoLayer};

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let addr = "127.0.0.1:8080";

    println!("Starting server on http://{}", addr);

    let ns = Namespace::builder()
        .add("/", |socket| async move {
            println!("Socket connected with id: {}", socket.sid);

            socket.on("ping", |socket, data: Value, bin, _| async move {
                println!("Received event: {:?} {:?}", data, bin);
                socket.bin(bin).emit("ping", "pong").ok(); 
            });
        })
        .build();

    let app = axum::Router::new()
        .route("/", get(|| async { "Server is listening!" }))
        .layer(SocketIoLayer::new(ns));

    Server::bind(&addr.parse().unwrap())
        .serve(app.into_make_service())
        .await?;

    Ok(())
}
```

Client:

```ts
// client.ts
import * as socketIo from "socket.io-client";

export const socket = socketIo.connect("http://localhost:8080", {
	autoConnect: false,
});

export const connect = () => socket.open();

socket.on("connect", async () => {
  console.log("connected");
	socket.emit("ping");
});

socket.on("pong", (message: string) => {
  console.log("pong", message);
});

socket.on("disconnect", () => {
	console.log("disconnected");
});

// main.ts
// import { connect } from './client';
// connect();
```

**Comment by Totodore** [comment]
You can add debug logs using `tracing subscriber` as shown in the axum-echo-example

**Comment by sleeyax** [comment]
Added but it nothing gets logged :thinking: 

client logs:
```
socket.io-client:url parse http://localhost:8080 +0ms
  socket.io-client new io instance for http://localhost:8080 +0ms
  socket.io-client:manager readyState closed +0ms
  socket.io-client:manager opening http://localhost:8080 +0ms
  engine.io-client:socket creating transport "polling" +0ms
  engine.io-client:polling polling +0ms
  engine.io-client:polling-xhr xhr poll +0ms
  engine.io-client:polling-xhr xhr open GET: http://localhost:8080/socket.io/?EIO=3&transport=polling&t=OZ8y5kY&b64=1 +1ms
  engine.io-client:polling-xhr xhr data null +0ms
  engine.io-client:socket setting transport polling +6ms
  socket.io-client:manager connect attempt will timeout after 20000 +6ms
  engine.io-client:socket socket error {"type":"TransportError","description":400} +6ms
  socket.io-client:manager connect_error +6ms
  socket.io-client:manager cleanup +0ms
  socket.io-client:manager will wait 855ms before reconnect attempt +1ms
  engine.io-client:socket socket close with reason: "transport error" +1ms
  engine.io-client:polling transport not open - deferring close +13ms
  socket.io-client:manager attempting reconnect +855ms
  socket.io-client:manager readyState closed +1ms
  socket.io-client:manager opening http://localhost:8080 +0ms
  engine.io-client:socket creating transport "polling" +856ms
  engine.io-client:polling polling +857ms
  engine.io-client:polling-xhr xhr poll +869ms
  engine.io-client:polling-xhr xhr open GET: http://localhost:8080/socket.io/?EIO=3&transport=polling&t=OZ8y5y8&b64=1 +0ms
  engine.io-client:polling-xhr xhr data null +0ms
  engine.io-client:socket setting transport polling +4ms
  socket.io-client:manager connect attempt will timeout after 20000 +4ms
  engine.io-client:socket socket error {"type":"TransportError","description":400} +4ms
  socket.io-client:manager connect_error +5ms
  socket.io-client:manager cleanup +0ms
  socket.io-client:manager reconnect attempt error +0ms
  socket.io-client:manager reconnect failed +0ms
  engine.io-client:socket socket close with reason: "transport error" +1ms
  engine.io-client:polling transport not open - deferring close +8ms
```

Looks like ` GET: http://localhost:8080/socket.io/?EIO=3&transport=polling&t=OZ8y5y8&b64=1` always results in a `400 Bad Request`.

**Comment by Totodore** [comment]
You are using socket io v3. Socketioxide only supports v4 for now.

**Comment by sleeyax** [comment]
Oh I see. Are there any plans for v3 support? I'm trying to integrate with an older application and unfortunately I can't upgrade the client to v4 yet.

**Comment by Totodore** [comment]
Yes V3 support is in the planned features

**Pull request merged**
