### PR TITLE
Fix compile error: Value used after being moved

### PR DESCRIPTION
**Pull request by tausifcreates**
Got this error message from my RustRover ide...don't know how RA missed that on vscode?

### CODE REVIEW

**Comment by Totodore** [comment]
I disagree, first if there was a real "used after move error" the compilation step would fail.

Also the payload is deconstructed and the bin is only used here.

Moreover cloning the bin payload would be a high bottleneck as it can be heavy (e.g. images).

**Comment by tausifcreates** [comment]
Unsure why my Rust plugin in Jetbrains is reporting weird error messages. Any thoughts?

**Comment by Totodore** [comment]
Try to compile through the command line.

**Comment by tausifcreates** [comment]
Noted.

**Pull request closed without merging**
