### PR TITLE
Fix extra byte in websocket binary frame on EIO v3

### LINKED ISSUE #277: Binary events sent to handlers have a 0x4 byte prepended to the binary data (v4 server)
**Describe the bug**

When socketioxide is acting as a v4 server, and a client sends a binary event, the `Vec<u8>` that is exposed to the handler has a `0x4` byte prepended to the otherwise-correct data.

**To Reproduce**

See https://github.com/kelnos/socketioxide-binary-test for a reproducer; README contains instructions for running it.

**Expected behavior**

Binary data should appear in the socketioxide handler as it was sent by the client, not with an extra `0x4` byte in front of the data.

**Versions (please complete the following information):**
 - Socketioxide version: 0.8.0 or 0.10.2
 - Http lib: warp 0.3 or axum 0.7.4
 - Socket.io client version: Java 1.0.2, JS 2.5.0
 
**Additional context**

There are no issues when socketioxide is acting as a v5 server.

### PR DESCRIPTION
**Pull request by kelnos**
In v3 of the engine.io protocol, the packet type byte is prepended to the binary data that is sent out on a websocket binary frame.  This byte needs to be stripped off the data before it's sent to the handler.

Closes #277.

### CODE REVIEW

**Comment by Totodore** [comment]
This test fails:
```rust
      it("sends and receives a binary packet", async () => {
        const socket = new WebSocket(
          `${WS_URL}/engine.io/?EIO=3&transport=websocket`
        );
        socket.binaryType = "arraybuffer";

        await waitFor(socket, "message"); // handshake

        socket.send(Uint8Array.from([4, 1, 2, 3, 4]));

        const { data } = await waitFor(socket, "message");

        expect(data).to.eql(Uint8Array.from([4, 1, 2, 3, 4]).buffer);

        socket.close();
      });
```

It is probably because, the 0x04 byte is not added at the beginning of the payload when the packet is sent back.
If you could check this it would be nice.

**Comment by Totodore** [comment]
https://github.com/Totodore/socketioxide/blob/main/engineioxide%2Fsrc%2Ftransport%2Fpolling%2Fpayload%2Fencoder.rs#L118

When encoding/decoding with polling the 0x04 prefix is added.
I think it would be better to insert the 0x04 prefix in the `packet` module at the creation of the binary packet because it is a common behaviour between all transports.

Indeed, I thought that the 0x04 prefix for binary was only supposed to be applied for polling payload whereas it should be always applied.

See https://github.com/Totodore/engine.io-protocol/tree/v3?tab=readme-ov-file#packet

**Comment by kelnos** [comment]
Hm, ok, so I looked through the `packet` module in engineioxide, and I can't seem to find a good place to put this.  There is only one place where the `BinaryV3` variant [is created](https://github.com/Totodore/socketioxide/blob/main/engineioxide/src/packet.rs#L163), and that appears to just be for the polling transport?  The `Binary` variant is -- I think? -- used for both v4 and v3-over-websocket, and the packet itself doesn't know the protocol version, so I don't think I can do it there, right?

This does seem to be very specific to the v3 websocket transport, no?  If I'm understanding things correctly, it seems like the intent is that `Packet::BinaryV3` should hold just the binary data itself, not any protocol-related details?

So I'm thinking that the place where I put the removal is correct, as that's right after it's received from the websocket, but right before it's passed to the handler: at that point the data needs to have the protocol details removed; the handler (e.g. `Client` in socketioxide) should never see that extra byte.  And then analogously, adding the byte before sending a binary packet should be done [in the transport](https://github.com/Totodore/socketioxide/blob/main/engineioxide/src/transport/ws.rs#L215) as well.

Anyhow, with that change, I was able to run the E2E tests, which pass now.  Pushed the update in case you think that's reasonable.  Otherwise happy to change it to whatever you think would be better.

**Comment by Totodore** [comment]
Ok, I agree with what you said about the `BinaryV3` variant and the impossibility to add the prefix in the packet module.

This may deserve some refactoring but it will be for later.

**Comment by kelnos** [comment]
Hm looks like the socketio v4 test is failing now, checking...

**Comment by kelnos** [comment]
Ok, looks like `Packet::Binary` is used for v3-over-websocket, so instead of just matching on `Packet::BinaryV3` it looks like I need to check `socket.protocol`.  socketioxide-e2e v4 is passing locally for me now too.  Hopefully the rest will still pass too...

**Comment by Totodore** [comment]
I will try to release a version with this patch included during the next week

**Comment by kelnos** [comment]
Great, thank you!

**Pull request merged**
